name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install and test
      run: |
        curl https://nixos.org/nix/install | sh
        . "$HOME"/.nix-profile/etc/profile.d/nix.sh
        ./test.bash
